# Download iris dataset file. Read this csv file using read_csv() function.  Take samples from entire dataset. Display maximum   and minimum values of all numeric attributes.

In [2]:
import pandas as pd

In [3]:
data=pd.read_csv("iris.csv")

In [4]:
data

     sepal_length  sepal_width  petal_length  petal_width    species
0             5.1          3.5           1.4          0.2     setosa
1             4.9          3.0           1.4          0.2     setosa
2             4.7          3.2           1.3          0.2     setosa
3             4.6          3.1           1.5          0.2     setosa
4             5.0          3.6           1.4          0.2     setosa
..            ...          ...           ...          ...        ...
145           6.7          3.0           5.2          2.3  virginica
146           6.3          2.5           5.0          1.9  virginica
147           6.5          3.0           5.2          2.0  virginica
148           6.2          3.4           5.4          2.3  virginica
149           5.9          3.0           5.1          1.8  virginica

[150 rows x 5 columns]

In [5]:
data.shape

(150, 5)

In [6]:
data.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 150 entries, 0 to 149
Data columns (total 5 columns):
 #   Column        Non-Null Count  Dtype
---  ------        --------------  -----
 0   sepal_length  150 non-null    float64
 1   sepal_width   150 non-null    float64
 2   petal_length  150 non-null    float64
 3   petal_width   150 non-null    float64
 4   species       150 non-null    object
dtypes: float64(4), object(1)
memory usage: 6.0+ KB

In [7]:
print("For Sepal Length\nMaximum value is:  ",data["sepal_length"].max(),"\nMinimum value is: ",data["sepal_length"].min())
print("\nFor Sepal Width\nMaximum value is:  ",data["sepal_width"].max(),"\nMinimum value is: ",data["sepal_width"].min())
print("\nFor Petal Length\nMaximum value is:  ",data["petal_length"].max(),"\nMinimum value is: ",data["petal_length"].min())
print("\nFor Petal Width\nMaximum value is:  ",data["petal_width"].max(),"\nMinimum value is: ",data["petal_width"].min())

For Sepal Length
Maximum value is:   7.9
Minimum value is:  4.3

For Sepal Width
Maximum value is:   4.4
Minimum value is:  2.0

For Petal Length
Maximum value is:   6.9
Minimum value is:  1.0

For Petal Width
Maximum value is:   2.5
Minimum value is:  0.1

In [8]:
data.describe()

       sepal_length  sepal_width  petal_length  petal_width
count    150.000000   150.000000    150.000000   150.000000
mean       5.843333     3.054000      3.758667     1.198667
std        0.828066     0.433594      1.764420     0.763161
min        4.300000     2.000000      1.000000     0.100000
25%        5.100000     2.800000      1.600000     0.300000
50%        5.800000     3.000000      4.350000     1.300000
75%        6.400000     3.300000      5.100000     1.800000
max        7.900000     4.400000      6.900000     2.500000